# Enable C++ support
language: cpp

os:
  - linux
  - os: osx
    osx_image: xcode9.2

# Compiler selection
compiler:
  - gcc
  - clang

# Build steps
script:
  - bash ./create-build.sh
  - bash ./run-tests.sh

